name: Deploy To Cloudflare  

on:  
  push:  
    branches:  
      - main  
  repository_dispatch:  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      
      - name: Install Dependencies  
        run: npm ci  # Use npm ci for clean installation of packages  

      - name: Install cheerio  
        run: npm install cheerio  
        
      - name: Install crypto-js  
        run: npm install crypto-js  
        
      - name: Build & Deploy Worker  
        uses: cloudflare/wrangler-action@v3  
        with:  
          apiToken: ${{ secrets.CF_API_TOKEN }}  
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
